default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        stages:
          - pre-commit

      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        stages:
          - pre-commit

      - id: mixed-line-ending
        args:
          - --fix=lf
        stages:
          - pre-commit

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: python Tools/CodeQuality/clang_format_hook.py
        language: system
        files: \.(c|cc|cpp|cxx|h|hpp|m|mm)$
        stages:
          - pre-commit

      - id: clang-format-check
        name: clang-format-check
        entry: python Tools/CodeQuality/clang_format_hook.py --check --all-files
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-push
